# 计算

# 数据分析

In [11]:
import pickle
import pathlib
import os
from collections import defaultdict

In [5]:
strategy_name = 'golden_cross'
result_dir = pathlib.Path('../white_quant/result/{}'.format(strategy_name))

In [12]:
data_result = defaultdict(None)
for item in result_dir.iterdir():
    print(item.name.split('.')[0])
    with item.open('rb') as f:
        data_result[item.name.split('.')[0]] = pickle.load(f)

000001
000063
600816

## summary数据分析

In [27]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
summary_index = []
summary_data= []
for key, value in data_result.items():
    index = summary_index.append(key)
    summary_data.append(value['sys_analyser']['summary'])
summary_df = pd.DataFrame(summary_data, index=summary_index)
summary_df

,strategy_name,start_date,end_date,strategy_file,run_type,STOCK,alpha,beta,sharpe,information_ratio,downside_risk,tracking_error,sortino,volatility,max_drawdown,total_value,cash,total_returns,annualized_returns,unit_net_value,units
000001,strategy,2018-06-01,2019-05-31,strategy.py,BACKTEST,100000.0,NaN,NaN,0.196,0.303,0.189,0.287,0.461,0.287,0.192,104554.972,1024.972,0.046,0.047,1.046,100000.0
000063,strategy,2018-06-01,2019-05-31,strategy.py,BACKTEST,100000.0,NaN,NaN,0.837,0.916,0.230,0.389,1.549,0.389,0.238,131286.556,1866.556,0.313,0.326,1.313,100000.0
600816,strategy,2018-06-01,2019-05-31,strategy.py,BACKTEST,100000.0,NaN,NaN,NaN,NaN,0.000,0.000,NaN,0.000,0.000,100000.000,100000.000,0.000,0.000,1.000,100000.0

In [23]:
data_result['000001']

{'sys_analyser': {'summary': {'strategy_name': 'strategy',
   'start_date': '2018-06-01',
   'end_date': '2019-05-31',
   'strategy_file': 'strategy.py',
   'run_type': 'BACKTEST',
   'STOCK': 100000.0,
   'alpha': nan,
   'beta': nan,
   'sharpe': 0.196,
   'information_ratio': 0.303,
   'downside_risk': 0.189,
   'tracking_error': 0.287,
   'sortino': 0.461,
   'volatility': 0.287,
   'max_drawdown': 0.192,
   'total_value': 104554.972,
   'cash': 1024.972,
   'total_returns': 0.046,
   'annualized_returns': 0.047,
   'unit_net_value': 1.046,
   'units': 100000.0},
  'trades':                         trading_datetime order_book_id symbol  side  \
  datetime
  2018-09-17 15:00:00  2018-09-17 15:00:00   000001.XSHE   平安银行   BUY
  2019-01-02 15:00:00  2019-01-02 15:00:00   000001.XSHE   平安银行  SELL
  2019-01-29 15:00:00  2019-01-29 15:00:00   000001.XSHE   平安银行   BUY

                      position_effect         exec_id     tax  commission  \
  datetime
  2018-09-17 15:00:00            OPEN  15681233970000   0.000     79.8456
  2019-01-02 15:00:00           CLOSE  15681233970001  94.657     75.7256
  2019-01-29 15:00:00            OPEN  15681233970002   0.000     74.8000

                       last_quantity  last_price        order_id  \
  datetime
  2018-09-17 15:00:00          10300        9.69  15681233960001
  2019-01-02 15:00:00          10300        9.19  15681233960002
  2019-01-29 15:00:00           8500       11.00  15681233960004

                       transaction_cost
  datetime
  2018-09-17 15:00:00           79.8456
  2019-01-02 15:00:00          170.3826
  2019-01-29 15:00:00           74.8000  ,
  'portfolio':                   cash  total_value  market_value  unit_net_value     units  \
  date
  2018-06-01  100000.000   100000.000           0.0         1.00000  100000.0
  2018-06-04  100000.000   100000.000           0.0         1.00000  100000.0
  2018-06-05  100000.000   100000.000           0.0         1.00000  100000.0
  2018-06-06  100000.000   100000.000           0.0         1.00000  100000.0
  2018-06-07  100000.000   100000.000           0.0         1.00000  100000.0
  ...                ...          ...           ...             ...       ...
  2019-05-27    1024.972   106169.972      105145.0         1.06170  100000.0
  2019-05-28    1024.972   107189.972      106165.0         1.07190  100000.0
  2019-05-29    1024.972   106424.972      105400.0         1.06425  100000.0
  2019-05-30    1024.972   104894.972      103870.0         1.04895  100000.0
  2019-05-31    1024.972   104554.972      103530.0         1.04555  100000.0

              static_unit_net_value
  date
  2018-06-01                  1.000
  2018-06-04                  1.000
  2018-06-05                  1.000
  2018-06-06                  1.000
  2018-06-07                  1.000
  ...                           ...
  2019-05-27                  1.060
  2019-05-28                  1.062
  2019-05-29                  1.072
  2019-05-30                  1.064
  2019-05-31                  1.049

  [243 rows x 6 columns],
  'stock_account':                   cash  transaction_cost  market_value  total_value  \
  date
  2018-06-01  100000.000               0.0           0.0   100000.000
  2018-06-04  100000.000               0.0           0.0   100000.000
  2018-06-05  100000.000               0.0           0.0   100000.000
  2018-06-06  100000.000               0.0           0.0   100000.000
  2018-06-07  100000.000               0.0           0.0   100000.000
  ...                ...               ...           ...          ...
  2019-05-27    1024.972               0.0      105145.0   106169.972
  2019-05-28    1024.972               0.0      106165.0   107189.972
  2019-05-29    1024.972               0.0      105400.0   106424.972
  2019-05-30    1024.972               0.0      103870.0   104894.972
  2019-05-31    1024.972               0.0      103530.0   104554.972

              dividend_receivable
  date
  2018-06-01                  0.0
  2018-06-04                  0.0
  2018-06-05                  0.0
  2018-06-06                  0.0
  2018-06-07                  0.0
  ...                         ...
  2019-05-27                  0.0
  2019-05-28                  0.0
  2019-05-29                  0.0
  2019-05-30                  0.0
  2019-05-31                  0.0

  [243 rows x 5 columns],
  'stock_positions':            order_book_id symbol  quantity  last_price  avg_price  market_value
  date
  2018-09-17   000001.XSHE   平安银行   10300.0        9.69       9.69       99807.0
  2018-09-18   000001.XSHE   平安银行   10300.0       10.08       9.69      103824.0
  2018-09-19   000001.XSHE   平安银行   10300.0       10.24       9.69      105472.0
  2018-09-20   000001.XSHE   平安银行   10300.0       10.23       9.69      105369.0
  2018-09-21   000001.XSHE   平安银行   10300.0       10.67       9.69      109901.0
  ...                  ...    ...       ...         ...        ...           ...
  2019-05-27   000001.XSHE   平安银行    8500.0       12.37      11.00      105145.0
  2019-05-28   000001.XSHE   平安银行    8500.0       12.49      11.00      106165.0
  2019-05-29   000001.XSHE   平安银行    8500.0       12.40      11.00      105400.0
  2019-05-30   000001.XSHE   平安银行    8500.0       12.22      11.00      103870.0
  2019-05-31   000001.XSHE   平安银行    8500.0       12.18      11.00      103530.0

  [150 rows x 6 columns]}}